In [ ]:
from mxnet import np, npx
npx.set_np()

x = np.array(3.0)
y = np.array(2.0)

x + y, x * y, x / y, x ** y

In [ ]:
A = np.arange(20).reshape(5, 4)
A

In [ ]:
A.T

In [ ]:
X = np.arange(24).reshape(2, 3, 4)
X
np.linalg.norm(X)

In [ ]:
A = np.arange(20).reshape(5, 4)
B = A.copy()  # Assign a copy of `A` to `B` by allocating new memory
A, A + B

In [ ]:
A * B

In [ ]:
A.shape, A.sum()

In [ ]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

In [ ]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

In [ ]:
A.sum(axis=[0, 1])  # Same as A.sum()

In [ ]:
A.mean(), A.sum() / A.size

In [ ]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

In [ ]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

In [ ]:
A / sum_A

In [ ]:
A.cumsum(axis=0)

In [ ]:
A

In [ ]:
x = np.arange(4)
y = np.ones(4)
x, y, np.dot(x, y)

In [ ]:
A.shape, x.shape, np.dot(A, x)

In [ ]:
B = np.ones(shape=(4, 3))
np.dot(A, B)

In [ ]:
u = np.array([3, -4])
np.linalg.norm(u)

In [ ]:
np.linalg.norm(np.ones((4, 9)))

In [ ]:
A/A.sum()

In [ ]:
%matplotlib inline
from d2l import mxnet as d2l
from IPython import display
from mxnet import np, npx
npx.set_np()

def f(x):
    return x ** 3 - 1 / x

In [ ]:
def numerical_lim(f, x, h):
    return (f(x + h) - f(x)) / h

h = 0.1
for i in range(5):
    print('h=%.5f, numerical limit=%.5f' % (h, numerical_lim(f, 1, h)))
    h *= 0.1

In [ ]:
def use_svg_display():  #@save
    """Use the svg format to display a plot in Jupyter."""
    display.set_matplotlib_formats('svg')

In [ ]:
def set_figsize(figsize=(3.5, 2.5)):  #@save
    """Set the figure size for matplotlib."""
    use_svg_display()
    d2l.plt.rcParams['figure.figsize'] = figsize

In [ ]:
#@save
def set_axes(axes, xlabel, ylabel, xlim, ylim, xscale, yscale, legend):
    """Set the axes for matplotlib."""
    axes.set_xlabel(xlabel)
    axes.set_ylabel(ylabel)
    axes.set_xscale(xscale)
    axes.set_yscale(yscale)
    axes.set_xlim(xlim)
    axes.set_ylim(ylim)
    if legend:
        axes.legend(legend)
    axes.grid()

In [ ]:
#@save
def plot(X, Y=None, xlabel=None, ylabel=None, legend=None, xlim=None,
         ylim=None, xscale='linear', yscale='linear',
         fmts=('-', 'm--', 'g-.', 'r:'), figsize=(3.5, 2.5), axes=None):
    """Plot data instances."""
    if legend is None:
        legend = []

    set_figsize(figsize)
    axes = axes if axes else d2l.plt.gca()

    # Return True if `X` (ndarray or list) has 1 axis
    def has_one_axis(X):
        return (hasattr(X, "ndim") and X.ndim == 1 or isinstance(X, list)
                and not hasattr(X[0], "__len__"))

    if has_one_axis(X):
        X = [X]
    if Y is None:
        X, Y = [[]] * len(X), X
    elif has_one_axis(Y):
        Y = [Y]
    if len(X) != len(Y):
        X = X * len(Y)
    axes.cla()
    for x, y, fmt in zip(X, Y, fmts):
        if len(x):
            axes.plot(x, y, fmt)
        else:
            axes.plot(y, fmt)
    set_axes(axes, xlabel, ylabel, xlim, ylim, xscale, yscale, legend)

In [ ]:
x = np.arange(0, 3, 0.1)
plot(x, [f(x), 2 * x - 3], 'x', 'f(x)', legend=['f(x)', 'Tangent line (x=1)'])

In [ ]:
from mxnet import autograd, np, npx
npx.set_np()

In [ ]:
x = np.arange(4.0)
x

In [ ]:
x.attach_grad()
x.grad

In [ ]:
with autograd.record():
    y = 2 * np.dot(x, x)
y

In [ ]:
y.backward()

In [ ]:
x.grad

In [ ]:
x.grad == 4 * x

In [ ]:
x = np.arange(4.0)
x
x.attach_grad()
x.grad
with autograd.record():
    y = 2 * np.dot(x, x)
y

In [ ]:
y.backward()

In [ ]:
x.grad

In [1]:
%matplotlib inline
from d2l import mxnet as d2l
from mxnet import np, npx
npx.set_np()

In [2]:
fair_probs = [1.0 / 6] * 6
np.random.multinomial(1, fair_probs)

array([0, 0, 0, 0, 0, 1], dtype=int64)

In [3]:
np.random.multinomial(10, fair_probs)

array([ 0,  0,  0,  0,  0, 10], dtype=int64)

In [4]:
counts = np.random.multinomial(10, fair_probs, size=3)
counts

array([[ 0,  0,  0,  0,  0, 10],
       [ 3,  0,  0,  0,  0,  7],
       [ 1,  2,  0,  0,  0,  7]], dtype=int64)

In [5]:
# Store the results as 32-bit floats for division
counts = np.random.multinomial(1000, fair_probs).astype(np.float32)
counts / 1000  # Relative frequency as the estimate

array([0., 0., 0., 0., 0., 1.])

In [ ]:
counts = np.random.multinomial(10, fair_probs, size=500)
cum_counts = counts.astype(np.float32).cumsum(axis=0)
estimates = cum_counts / cum_counts.sum(axis=1, keepdims=True)

d2l.set_figsize((6, 4.5))
for i in range(6):
    d2l.plt.plot(estimates[:, i].asnumpy(),
                 label=("P(die=" + str(i + 1) + ")"))
d2l.plt.axhline(y=0.167, color='black', linestyle='dashed')
d2l.plt.gca().set_xlabel('Groups of experiments')
d2l.plt.gca().set_ylabel('Estimated probability')
d2l.plt.legend();

In [6]:
help(np.ones_like)

Help on function ones_like in module mxnet.numpy:

ones_like(a)
    Return an array of ones with the same shape and type as a given array.
    
    Parameters
    ----------
    a : ndarray
        The shape and data-type of `a` define these same attributes of
        the returned array.
    
    Returns
    -------
    out : ndarray
        Array of ones with the same shape and type as `a`.
    
    Examples
    --------
    >>> x = np.arange(6)
    >>> x = x.reshape((2, 3))
    >>> x
    array([[0., 1., 2.],
           [3., 4., 5.]])
    >>> np.ones_like(x)
    array([[1., 1., 1.],
           [1., 1., 1.]])
    
    >>> y = np.arange(3, dtype=float)
    >>> y
    array([0., 1., 2.], dtype=float64)
    >>>
    >>> np.ones_like(y)
    array([1., 1., 1.], dtype=float64)



In [9]:
np.ones_like??